; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32s3]
platform = espressif32@ 6.5.0
board = esp32s3
framework = arduino #espidf
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, colorize
build_type = debug
; build_flags =  -D USE_HSPI_PORT = 1
#lib_deps = fastled/FastLED@^3.6.0
build_flags = 
  -I lib/GUI/generated/guider_customer_fonts 
  -I lib/GUI/generated 
  -I lib/GUI/custom 

; 指定多个源文件目录
; src_dir = 
;     src
;     lib

; src_filter = 
;     ; +<*>  
;     +<src> 
;     +<include>
;     +<lib/GUI/custom> 
;     +<lib/GUI/generated>
;     -<lib/GUI/import> 
;     -<lib/GUI/lib> 
;     -<lib/GUI/lvgl/*> 
;     -<lib/GUI/lvgl-simulator/*> 
;     -<lib/GUI/lvgl-simulator/gg_external_data/freemaster/*> 
;     -<lib/GUI/ports/*> 
;     -<lib/GUI/temp/*>
;  -<*>  
; src_filter = +<*> -<GUI/**> -<GUI/import/**> -<GUI/lib/**> -<GUI/lvgl/**> -<lib/GUI/lvgl-simulator/*.c> 
lib_deps = 
          fastled/FastLED @ ^3.10.1
          philj404/SimpleSerialShell@^1.0.0
          bodmer/TFT_eWidget @ ^0.0.6
          bodmer/TFT_eSPI @ ^2.5.43
          lvgl/lvgl @ ^9.1.0
          ; vshymanskyy/Preferences @ ^2.1.0
          ; lorol/LittleFS_esp32 @ ^1.0.6