; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32s3]
platform = espressif32@ 6.5.0
board = esp32s3
framework = arduino #espidf
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, colorize
build_type = debug
; build_flags =  -D USE_HSPI_PORT = 1
#lib_deps = fastled/FastLED@^3.6.0
build_flags = 
  -I lib/GUI/generated/guider_customer_fonts 
  ; -I lib/GUI/generated 
  -I lib/GUI/custom 
  -I include

  -D USER_SETUP_LOADED=1  ; 定义此宏，跳过库的默认配置加载
  -D ST7789_DRIVER       ; 指定屏幕驱动
  -D TFT_WIDTH=240        ; 屏幕宽度
  -D TFT_HEIGHT=240       ; 屏幕高度
  -D TFT_SCLK=41           ; SCK引脚
  -D TFT_MOSI=40          ; MOSI引脚
  -D TFT_CS=42             ; CS引脚
  -D TFT_DC=43            ; DC引脚
  -D TFT_RST=39           ; RST引脚
  -D TFT_BL=38           ; BL引脚
  -D SPI_FREQUENCY=40000000  ; SPI速度
  
  -D CORE_DEBUG_LEVEL=5  ; 设置调试级别 (0-5)
lib_deps = 
          fastled/FastLED @ ^3.10.1
          philj404/SimpleSerialShell@^1.0.0
          bodmer/TFT_eWidget @ ^0.0.6
          bodmer/TFT_eSPI @ ^2.5.43
          lvgl/lvgl @ ^8.4.0
          bblanchon/ArduinoJson @ ^7.4.2
          ; vshymanskyy/Preferences @ ^2.1.0
          ; lorol/LittleFS_esp32 @ ^1.0.6